apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        prometeus.io/port: "8080"
        prometeus.io/path: "/metrics"
        prometeus.io/scrape: "true"
    spec:
      containers:
      - name: api
        image: andersoncmciet/springboot-test-ci:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "150m"
            memory: "32Mi"
          limits:
            cpu: "300m"
            memory: "64Mi"

--- 
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - name: http
      port: 8080

--- 
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-as
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: api
 minReplicas: 2
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50